swagger: "2.0"

info:
  version: 0.0.1
  title: Common elements
  description: Shared elements in all API

definitions:
  ViewResponse:
    description: "View Rendering시 필요한 기본 변수"
    type: "object"
    required:
      - logined
      - title
      - msg
    properties:
      ENV:
        type: object
        example:
          NODE_ENV: "development"
      logined:
        type: boolean
        default: false
      title:
        description: "사이트 제목(i18n값)"
        type: string
        example: "main"


  HelloWorldMessage:
    description: "hello world Message"
    type: "object"
    required:
      - message
    properties:
      message:
        type: string
        example: "hello 롯데월드!"

  PlainMessage:
    description: "Plain Object Message"
    type: "object"
    required:
      - message
    properties:
      message:
        type: string
        example: The protected test route is functional!


  ErrorResponse:
    required:
      - code
      - message
    properties:
      code:
        type: string
        enum:
          - DBERR
          - NTERR
          - UNERR
        example: UNERR
      message:
        $ref: '#/definitions/ErrorMessage'
    example:
      code: DBERR
      message:
        longMessage: "long message"
        shortMessage: "short message"

  ErrorMessage:
    required:
      - longMessage
      - shortMessage
    properties:
      longMessage:
        description: A long error description
        type: string
      shortMessage:
        description: A short error description
        type: string
