swagger: "2.0"

info:
  version: 0.0.1
  title: Common elements
  description: Shared elements in all API

definitions:
  HelloWorldMessage:
    description: "hello world Message"
    type: "object"
    required:
      - message
    properties:
      message:
        type: string
        example: "hello 롯데월드!"

  PlainMessage:
    description: "Plain Object Message"
    type: "object"
    required:
      - message
    properties:
      message:
        type: string
        example: The protected test route is functional!


  ErrorResponse:
    required:
      - code
      - msg
    properties:
      code:
        type: number
        enum:
          - badRequest_400
          - unauthorized_401
          - forbidden_403
          - notFound_404
          - internalServerError_500
      msg:
        description: A error description
        type: string
    example:
      code: badRequest_400
      msg: "error message"
