swagger: "2.0"

info:
  version: 0.0.1
  title: Common definition elements
  description: Shared definition in all API

definitions:
   HelloWorldMessage:
   description: "hello world Message"
    type: "object"
    required:
      - message
    properties:
      message:
        type: string

   PlainObjectMessage:
   description: "Plain Object Message"
    type: "object"

  Error:
    title: MultiLingualMultiDeviceError
    description: Give full information about the problem
    required:
      - code
      - message
    properties:
      code:
        description: A human readable code (death to numeric error codes!)
        type: string
        enum:
          - DBERR
          - NTERR
          - UNERR
        example: UNERR
      message:
        $ref: '#/definitions/ErrorMessage'

  ErrorMessage:
    title: MultiDeviceErrorMessage
    description: An error message with a long and a short description
    required:
      - longMessage
      - shortMessage
    properties:
      longMessage:
        description: A long error description
        type: string
      shortMessage:
        description: A short error description
        type: string
