swagger: "2.0"

info:
  version: 0.0.1
  title: address definition

definitions:
  Address:
    description: "주소 정보 전송을 위한 object"
    type: "object"
    required:
      - postCode
      - addr1
      - addr2
      - locale
    properties:
      postCode:
        type: "string"
        description: "우편번호(5자리), 시/구 구분에 쓰임"
      regionCode:
        type: string
        description: "법정동/법정리 코드, 동 구분용, ex> 4511310700 - 전라북도 전주시 덕진구 금암동"
      addr1:
        type: string
        description: "도로명 주소"
      addr2:
        type: string
        description: "지번 주소(기존 주소)"
      detail:
        type: string
        description: "상세 주소"
      extraInfo:
        type: string
        description: "참고 항목"
      locale:
        $ref: "./commons.yaml#/definitions/Locale"
    example:
      $ref: '#/definitions/AddressExample'


  AddressExample:
    postCode: 54922
    regionCode: 4511310500
    addr1: "전북 전주시 덕진구 백제대로 567"
    addr2: "전라북도 전주시 덕진구 금암동 1587-31"
    detail: "전북대학교 창업동아리 아늑한집"
    extraInfo: "전북대"
    locale: "ko-kr"
