swagger: "2.0"

info:
  version: 0.0.1
  title: coordinate definition

definitions:
  Coordinate:
    description: "좌표 정보 전송을 위한 object"
    type: "object"
    required:
      - lat
      - lng
    properties:
      regionCode:
        type: string
        description: "법정동/법정리 코드, 동 구분용, ex> 4511310700 - 전라북도 전주시 덕진구 금암동"
      lat:
        type: number
        format: double
        description: "주소에 해당하는 위도, ex> 35.8598743"
      lng:
        type: number
        format: double
        description: "주소에 해당하는 경도, ex> 127.1117673"
    example:
      $ref: "#/definitions/CoordinateExample"


  CoordinateExample:
    regionCode: "4511310700"
    lat: 35.8598743
    lng: 127.1117673
