swagger: "2.0"

info:
  version: 0.0.1
  title: media definition

definitions:
  Media:
    description: "미디어 정보 전송을 위한 object, 게시물 작성시 이용된 이미지/동영상/VR이미지/VR동영상등"
    type: "object"
    required:
      - type
      - date
      - file_path
      - file_name
    properties:
      ID:
        type: integer
        description: "Primary key"
      user_id:
        type: integer
        description: "user.ID의 FK"
      group:
        type: string
        description: "Media 파일의 목적별 관리를 위한 용도, 없는 경우 NULL, 있는 경우 고유 Key 생성"
      type:
        type: string
        description: "NORMAL_IMAGE, VR_IMAGE, VTOUR, VTOUR_CUSTOM, NORMAL_VIDEO, VR_VIDEO, AUDIO, PROFILE_IMAGE"
        enum:
          - "NORMAL_IMAGE"
          - "VR_IMAGE"
          - "VTOUR"  # vr이미지 원본
          - "VTOUR_CUSTOM"
          - "NORMAL_VIDEO"  # vr viewer
          - "VR_VIDEO"
          - "AUDIO"
          - "PROFILE_IMAGE"
      date:
        type: string
        format: 'date-time'
        description: "최초생성시간, UTC Time For Internationalization, format('YYYY-MM-DD HH:mm:ss')"
      file_path:
        type: string
        description: 폴더 경로 (ex> 1474243481136)
      file_name:
        type: string
        description: |
          파일 이름(ex> SAM_100_0008.jpg, tour.xml, tour.html) <br />
          원본 이름을 저장한다. <br />
          - 로딩 할 경우에는 image-server 서버로 request한다. <br />
          - type이 'VTOUR'일 경우 : xml 파일 이름으로 지정한다. <br />
          - type이 'VTOUR_CUSTOM'일 경우 : html 파일 이름으로 지정한다. <br />
      meta_value:
        $ref: '#/definitions/MetaValue'
    example:
      $ref: '#/definitions/MediaExample'


  MediaExample:
    ID: 5
    user_id: 2
    group: "5852a2215fa82"
    type: "VTOUR"
    date: "2017-05-20 20:15:54"
    file_path: "1474243481136"
    file_name: "SAM_100_0008.jpg"
    meta_value:
      $ref: '#/definitions/MetaValueExample'

  MediasExample:
  - ID: 5
    user_id: 2
    group: "5852a2215fa82"
    type: "VTOUR"
    date: "2017-05-20 20:15:54"
    file_path: "1474243481136"
    file_name: "SAM_100_0008.jpg"
    meta_value:
      $ref: '#/definitions/MetaValueExample'
  - ID: 6
    user_id: 3
    group: "5852a2215fa82"
    type: "VTOUR"
    date: "2017-05-20 20:15:57"
    file_path: "1474243484879"
    file_name: "SAM_100_0009.jpg"
    meta_value:
      $ref: '#/definitions/MetaValueExample'



  MetaValue:
    description: |
      composite, media 관련 부가 정보가 필요한 경우(JSON{}) <br /> <br />

      ex> NORMAL_IMAGE, PROFILE_IMAGE 저장시 <br />
      meta_value: { <br />
        mimetype: 'image/jpeg', <br />
        size: 14588725, <br />
        encoding: "7bit" <br />
      } <br /><br />

      ex> VR_IMAGE 저장시 <br />
      meta_value: { <br />
        mimetype: 'image/jpeg', <br />
        size: 14588725, <br />
        encoding: "7bit", <br />
        tile_dir_name: "SAM_100_0008.tiles", <br />
        thumbnail_image_name: "thumb.jpg",// 단일면 이미지 <br />
        preview_image_name: "preview.jpg",// 세로형 이미지(각 면->하나의 이미지) <br />
        mobile_dir_name: "mobile"  // 모바일용 이미지 저장 폴더 이름 <br />
      } <br /><br />

      ex> VTOUR 저장시 <br />
      meta_value: { <br />
        html_name: "tour.html",  // 로딩시 html 파일 이름 <br />
        js_name: "tour.js",  // 로딩시 js 파일 이름 <br />
        swf_name: "tour.swf",  // 로딩시 swf 파일 이름 <br />
        editor_name: "tour_editor.html",  // 로딩시 editor 파일 이름 <br />
        tile_dir_name: ["SAM_100_0008.tiles", "SAM_100_0009.tiles", ...],  // 원본 VR 이미지의 tile 경로 <br />
        original_media_id: [1, 3, 4, ...] // 원본 VR 이미지의 media.ID <br />
      } <br /><br />

      ex> multer 이용시 <br />
      meta_value: { <br />
        mimetype: value.mimetype, <br />
        size: value.size, <br />
        encoding: value.encoding <br />
      } <br /><br />

      ex> VTOUR_CUSTOM 저장시 <br />
      meta_value: { <br />
        * dir_name: "indexdata" <br />
      } <br />
    type: "object"
    properties:
      mimetype:      # 기본
        type: string
        description: mimetype, multer를 이용하는 경우 value.mimetype
      size:      # 기본
        type: integer
        description: file size, multer를 이용하는 경우 value.size
      encoding:      # 기본
        type: string
        description: file encoding, multer를 이용하는 경우 value.encoding
      tile_dir_name:      # VR_IMAGE, VTOUR 저장시
        type: array
        items:
          type: string
        description: "원본 VR 이미지의 tile 경로(media.meta_value.tile_dir_name), VR_IMAGE의 경우 string / VTOUR의 경우 string[] 형태임"
        example:
          - "SAM_100_0008.tiles"
          - "SAM_100_0009.tiles"
          - "SAM_100_0010.tiles"
      thumbnail_image_name:      # VR_IMAGE 저장시
        type: string
        description: 단일면 기준 미리보기 이미지, 현재는 pano_f(front)를 기준으로 생성됨, "VR_IMAGE"용
        default: "thumb.jpg"
      preview_image_name:      # VR_IMAGE 저장시
        type: string
        description: 세로형 기준 미리보기 이미지, 각 6개 면-> 직사각형 형태의 하나의 이미지로 제작함, "VR_IMAGE"용
        default: "preview.jpg"
      mobile_dir_name:      # VR_IMAGE 저장시
        type: "string"
        description: 모바일용 이미지 저장 폴더 이름, "VR_IMAGE"용
      html_name:      # VTOUR 저장시
        type: string
        description: 로딩시 html 파일 이름
        default: tour.html
      js_name:      # VTOUR 저장시
        type: string
        description: 로딩시 js 파일 이름
        default: "tour.js"
      swf_name:      # VTOUR 저장시
        type: string
        description: 로딩시 swf 파일 이름
        default: "tour.swf"
      editor_name:      # VTOUR 저장시
        type: string
        description: 로딩시 editor 파일 이름
        default: "tour_editor.html"
      original_media_id:      # VTOUR 저장시
        type: array
        items:
          type: integer
        description: 원본 VR 이미지의 media.ID
        example:
          - 1
          - 3
          - 4
      dir_name:      # VTOUR_CUSTOM 저장시
        type: string
        description: 압축 해제시 최초 폴더 이름(panotour로 제작한 Custom VTour 적용 가능)

  MetaValueExample:
    html_name: "tour.html"
    js_name: "tour.js"
    swf_name: "tour.swf"
    editor_name: "tour_editor.html"
    tile_dir_name:
      - "SAM_100_0008.tiles"
      - "SAM_100_0009.tiles"
    original_media_id:
      - 1
      - 3
      - 4
